
import javax.swing.JComboBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author instantcrush
 */
public class HospitalFrame extends javax.swing.JFrame {

    /**
     * Creates new form hospitalFrame
     */
    
    Departments department = null;
    Doctor doctor = null;
    Nurse nurse = null;
    Patient patient = null;
    
    //To know combo box states
    int state = 0;
    
    public HospitalFrame() {
        initComponents();
        
        //My codes
        jLabel1.setText(Hospital.hospitalName + " Information Systems");
        jPanel2.setVisible(false);
        jPanel4.setVisible(false);
        jPanel3.setVisible(false);
        jPanel6.setVisible(false);
        jPanel5.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        patientAdd = new javax.swing.JButton();
        patientClean = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        departmentAdd = new javax.swing.JButton();
        departmentClean = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        nurseAdd = new javax.swing.JButton();
        nurseClean = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        doctorAdd = new javax.swing.JButton();
        doctorClean = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        errorSuccess = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        areaClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Akkadian", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(229, 30, 30));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 794, 24));

        jLabel2.setText("Add:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 79, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Department", "Staff", "Patient", "" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 74, -1, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setText("Patient's name:");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));
        jPanel6.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 12, 100, -1));

        jLabel29.setText("Surname:");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, -1, -1));
        jPanel6.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 58, 100, -1));

        jLabel30.setText("Birthdate:");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 109, -1, -1));
        jPanel6.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 104, 100, -1));

        jLabel31.setText("Gender:");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 155, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel6.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 150, -1, -1));

        jLabel32.setText("Age:");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 196, -1, -1));
        jPanel6.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 196, 100, -1));

        jLabel33.setText("Entrance date:");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 247, -1, -1));
        jPanel6.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 242, 100, -1));

        jLabel34.setText("Sickness:");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 293, -1, -1));
        jPanel6.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 288, 100, -1));

        jLabel35.setText("Doctor name:");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 343, -1, -1));
        jPanel6.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 338, 100, -1));

        jLabel36.setText("Nurse name:");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 389, -1, -1));
        jPanel6.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 384, 100, -1));

        patientAdd.setText("ADD");
        patientAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientAddActionPerformed(evt);
            }
        });
        jPanel6.add(patientAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 70, -1));

        patientClean.setText("CLEAN");
        jPanel6.add(patientClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 70, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 120, -1, -1));

        jPanel5.setPreferredSize(new java.awt.Dimension(282, 552));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setText("Department Name:");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 55, -1, -1));

        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 50, 125, -1));

        jLabel26.setText("Department Block:");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 101, -1, -1));
        jPanel5.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 96, 125, -1));

        jLabel27.setText("Patient Capacity:");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 142, -1, -1));
        jPanel5.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 142, 125, -1));

        departmentAdd.setText("ADD");
        departmentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentAddActionPerformed(evt);
            }
        });
        jPanel5.add(departmentAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 110, -1));

        departmentClean.setText("CLEAN");
        departmentClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentCleanActionPerformed(evt);
            }
        });
        jPanel5.add(departmentClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 110, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 70, 320, 502));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Nurse" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Nurse's name: ");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 23, -1, -1));
        jPanel4.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 18, 100, -1));

        jLabel15.setText("Surname:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 69, -1, -1));
        jPanel4.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 64, 100, -1));

        jLabel16.setText("Birthdate:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 115, -1, -1));
        jPanel4.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 110, 100, -1));

        jLabel17.setText("Gender:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 207, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel4.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 202, -1, -1));

        jLabel18.setText("ID:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 156, -1, -1));
        jPanel4.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 156, 100, -1));

        jLabel19.setText("Position:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 248, -1, -1));
        jPanel4.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 248, 100, -1));

        jLabel20.setText("Salary:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 432, -1, -1));
        jPanel4.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 432, 100, -1));

        jLabel22.setText("Doctor no:");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 299, -1, -1));
        jPanel4.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 294, 100, -1));

        jLabel23.setText("Department Name:");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 340, -1, -1));
        jPanel4.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 340, 100, -1));

        jLabel24.setText("Department Block:");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 391, -1, -1));

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 386, 100, -1));

        nurseAdd.setText("ADD");
        nurseAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseAddActionPerformed(evt);
            }
        });
        jPanel4.add(nurseAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 90, -1));

        nurseClean.setText("CLEAN");
        nurseClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseCleanActionPerformed(evt);
            }
        });
        jPanel4.add(nurseClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 100, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 52, 270, 500));
        jPanel4.getAccessibleContext().setAccessibleParent(jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Doctor's name: ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, -1, -1));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 12, 100, -1));

        jLabel4.setText("Surname:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, -1, -1));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 58, 100, -1));

        jLabel5.setText("Birthdate:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 109, -1, -1));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 104, 100, -1));

        jLabel6.setText("Gender:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 201, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 196, -1, -1));

        jLabel7.setText("ID:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 150, -1, -1));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 150, 100, -1));

        jLabel8.setText("Position:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 242, -1, -1));
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 242, 100, -1));

        jLabel9.setText("Salary:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 100, -1));

        jLabel10.setText("Speciality:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 288, -1, -1));
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 288, 100, -1));

        jLabel11.setText("Room no:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 339, -1, -1));
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 334, 100, -1));

        jLabel12.setText("Department Name:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 380, -1, -1));
        jPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 380, 100, -1));

        jLabel13.setText("Department Block:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 431, -1, -1));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 426, 100, -1));

        doctorAdd.setText("ADD");
        doctorAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorAddActionPerformed(evt);
            }
        });
        jPanel3.add(doctorAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 90, -1));

        doctorClean.setText("CLEAN");
        doctorClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorCleanActionPerformed(evt);
            }
        });
        jPanel3.add(doctorClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 100, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 52, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 121, -1, -1));

        jLabel21.setText("Enter ID:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 73, -1, -1));
        jPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 74, 120, -1));
        jPanel1.add(errorSuccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 49, 540, 18));

        jButton1.setText("Display");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 70, 40));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 70, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 380, 540));

        areaClean.setText("CLEAN");
        areaClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaCleanActionPerformed(evt);
            }
        });
        jPanel1.add(areaClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 680, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        if(jComboBox1.getSelectedIndex() == 0) {
            state = 0;
            jPanel2.setVisible(false);
            jPanel5.setVisible(true);
            jPanel6.setVisible(false);
            
        } else if (jComboBox1.getSelectedIndex() == 1) {
            state = 1;
            jPanel2.setVisible(true);
            jPanel5.setVisible(false);
            jPanel6.setVisible(false);
            
        } else if (jComboBox1.getSelectedIndex() == 2) {
            state = 2;
            jPanel5.setVisible(false); //for departments
            jPanel2.setVisible(false); //for staff
            jPanel6.setVisible(true); //for patient
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
 
        if(state == 1) {
            
            if(jComboBox2.getSelectedIndex() == 0) {
            
                jPanel4.setVisible(false);
                jPanel3.setVisible(true);
            
            }
            if (jComboBox2.getSelectedIndex() == 1) {
                
                jPanel4.setVisible(true);
                jPanel3.setVisible(false);
            }
            
        }
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void departmentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentAddActionPerformed
        // TODO add your handling code here:
        if(state == 0) {
            try {
            
                if(jTextField21.getText().isEmpty() || jTextField22.getText().isEmpty() || jTextField23.getText().isEmpty()) {
                    throw new Exception();
                } else {

                    try {

                        int patientCapacity = Integer.parseInt(jTextField23.getText());
                        department = new Departments(jTextField21.getText(), jTextField22.getText(),patientCapacity);
                        errorSuccess.setText(jTextField21.getText() + "'s profile has successfully created!");

                    } catch (NumberFormatException e) {

                        errorSuccess.setText("Patient capacity must be given as integer!");

                    }
                }
            
            } catch (Exception e) {

                errorSuccess.setText("Above information cannot be empty!");

            }
        }
        
    }//GEN-LAST:event_departmentAddActionPerformed

    private void departmentCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentCleanActionPerformed
        // TODO add your handling code here:
        jTextField21.setText("");
        jTextField22.setText("");
        jTextField23.setText("");
    }//GEN-LAST:event_departmentCleanActionPerformed

    private void doctorAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorAddActionPerformed
        // TODO add your handling code here:
        try {
            
            if(jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty()
                    || jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty() || jTextField7.getText().isEmpty()
                    || jTextField8.getText().isEmpty() || jTextField9.getText().isEmpty() || jTextField10.getText().isEmpty()
                    || jTextField6.getText().isEmpty()) {
                throw new Exception();
            } else {
                
                try {
                    int doctorID = Integer.parseInt(jTextField4.getText());
                    String gender = null;
                    
                    if(jComboBox3.getSelectedIndex() == 0) {
                        gender = "male"; 
                    } else if (jComboBox3.getSelectedIndex() == 1){
                        gender = "female";
                    }
                     
                    
                    doctor = new Doctor(jTextField1.getText(), jTextField2.getText(), jTextField3.getText(),
                            gender, doctorID, jTextField5.getText(), Double.parseDouble(jTextField6.getText()), jTextField7.getText(),
                            Integer.parseInt(jTextField8.getText()), jTextField9.getText(), jTextField10.getText());
                    
                    Hospital.addStaff(doctor);
                    
                    errorSuccess.setText(jTextField1.getText() + "'s profile has successfully created!");
                    
                } catch (NumberFormatException e) {
                    
                    errorSuccess.setText("ID must be given as integer!");
                    
                }
            }
            
        } catch (Exception e) {
            
            errorSuccess.setText("Above information cannot be empty!");
            
        }
    }//GEN-LAST:event_doctorAddActionPerformed

    private void doctorCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorCleanActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText(""); 
        jTextField10.setText("");
        jTextField6.setText("");
    }//GEN-LAST:event_doctorCleanActionPerformed

    private void nurseAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseAddActionPerformed
        // TODO add your handling code here:
        try {
            
            if(jTextField11.getText().isEmpty() || jTextField12.getText().isEmpty() || jTextField13.getText().isEmpty()
                    || jTextField14.getText().isEmpty() || jTextField15.getText().isEmpty() 
                    || jTextField18.getText().isEmpty() || jTextField19.getText().isEmpty() || jTextField20.getText().isEmpty()
                    || jTextField16.getText().isEmpty()) {
                throw new Exception();
            } else {
                
                try {
                    int nurseID = Integer.parseInt(jTextField14.getText());
                    String nurseGender = null;
                    
                    if(jComboBox4.getSelectedIndex() == 0) {
                        nurseGender = "male"; 
                    } else if (jComboBox4.getSelectedIndex() == 1){
                        nurseGender = "female";
                    }
                     
                    
                    nurse = new Nurse(jTextField11.getText(), jTextField12.getText(), jTextField13.getText(),
                            nurseGender, nurseID, jTextField15.getText(), Double.parseDouble(jTextField16.getText()),
                            Integer.parseInt(jTextField18.getText()), jTextField19.getText(), jTextField20.getText());
                    
                    Hospital.addStaff(nurse);
                    
                    errorSuccess.setText(jTextField11.getText() + "'s profile has successfully created!");
                    
                } catch (NumberFormatException e) {
                    
                    errorSuccess.setText("ID must be given as integer!");
                    
                }
            }
            
        } catch (Exception e) {
            
            errorSuccess.setText("Above information cannot be empty!");
            
        }
    }//GEN-LAST:event_nurseAddActionPerformed

    private void nurseCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseCleanActionPerformed
        // TODO add your handling code here:
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField18.setText("");
        jTextField19.setText(""); 
        jTextField20.setText("");
        jTextField16.setText("");
    }//GEN-LAST:event_nurseCleanActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void areaCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaCleanActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
    }//GEN-LAST:event_areaCleanActionPerformed

    private void patientAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientAddActionPerformed
        // TODO add your handling code here:
        
        try {
            
            if(jTextField24.getText().isEmpty() || jTextField25.getText().isEmpty() || jTextField26.getText().isEmpty()
                    || jTextField27.getText().isEmpty() || jTextField28.getText().isEmpty() 
                    || jTextField29.getText().isEmpty() || jTextField30.getText().isEmpty() || jTextField31.getText().isEmpty()) {
                throw new Exception();
            } else {
                
                try {
                    int patientAge = Integer.parseInt(jTextField27.getText());
                    String patientGender = null;
                    
                    if(jComboBox5.getSelectedIndex() == 0) {
                        patientGender = "male"; 
                    } else if (jComboBox5.getSelectedIndex() == 1){
                        patientGender = "female";
                    }
                     
                    
                    patient = new Patient(jTextField24.getText(), jTextField25.getText(), jTextField26.getText(),
                            patientGender, patientAge, jTextField28.getText(), jTextField29.getText(),
                            jTextField30.getText(), jTextField31.getText());
                    
                    errorSuccess.setText(jTextField11.getText() + "'s profile has successfully created!");
                    
                } catch (NumberFormatException e) {
                    
                    errorSuccess.setText("Age must be given as integer!");
                    
                }
            }
            
        } catch (Exception e) {
            
            errorSuccess.setText("Above information cannot be empty!");
            
        }
    }//GEN-LAST:event_patientAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int searchId = Integer.parseInt(jTextField17.getText());
        String message = Hospital.searchId(searchId);
        jTextArea1.setText(message);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int delId = Integer.parseInt(jTextField17.getText());
        String message = Hospital.delId(delId);
        jTextArea1.setText(message);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton areaClean;
    private javax.swing.JButton departmentAdd;
    private javax.swing.JButton departmentClean;
    private javax.swing.JButton doctorAdd;
    private javax.swing.JButton doctorClean;
    private javax.swing.JLabel errorSuccess;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton nurseAdd;
    private javax.swing.JButton nurseClean;
    private javax.swing.JButton patientAdd;
    private javax.swing.JButton patientClean;
    // End of variables declaration//GEN-END:variables
}
